---

- name: Include create.yml to create Networks
  ansible.builtin.include_tasks: create.yml
  loop: "{{ hcloud_networks.keys() | list }}"
  loop_control:
    loop_var: network_item
  when: hcloud_networks is defined and hcloud.config.network.keys() | list | length > 0

- name: Include delete.yml to delete Networks
  ansible.builtin.include_tasks: delete.yml
  loop: "{{ hcloud_networks.keys() | list }}"
  loop_control:
    loop_var: network_item
  when: hcloud_networks is defined and hcloud.config.network.keys() | list | length > 0
